# -*- coding: utf-8 -*-
"""CSE221 lab1 task 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XsgFObO0fRzPWX0-3DtdCpy72MwHPP38
"""

input_file=open("input1a.txt",'r')
output_file=open("output1a.txt",'w')
red=input_file.readline()
total=int(red)
for i in range(total):
    next_lne=input_file.readline()
    var=int(next_lne)
    if var%2==0:
        res=str(var)+' is an even number.\n'
    else:
        res=str(var)+' is an odd number.\n'
    output_file.write(res)
input_file.close()
output_file.close()