# -*- coding: utf-8 -*-
"""CSE221 lab1 task 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XsgFObO0fRzPWX0-3DtdCpy72MwHPP38
"""

input_file=open("input1b.txt",'r')
output_file=open("output1b.txt",'w')
red=int(input_file.readline())
for i in range(red):
    next_reds=input_file.readline()
    var=next_reds.split()
    if var[2]=="+":
       result=int(var[1])+int(var[3])
       res=f' The result of {var[1]} + {var[3]} is {result}.\n'
    elif var[2]=="-":
       result=int(var[1])-int(var[3])
       res=f' The result of {var[1]} - {var[3]} is {result}.\n'
    elif var[2]=="/":
       result=int(var[1])-int(var[3])
       res=f' The result of {var[1]} / {var[3]} is {result}.\n'
    else:
       result=int(var[1])*int(var[3])
       res=f' The result of {var[1]} * {var[3]} is {result}.\n'
    output_file.write(res)
input_file.close()
output_file.close()