# -*- coding: utf-8 -*-
"""CSE221 lab1 task 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XsgFObO0fRzPWX0-3DtdCpy72MwHPP38
"""

input_file=open("input3.txt","r")
output_file=open("output3.txt","w")
red=int(input_file.readline())
arr1=input_file.readline().split()
arr2=input_file.readline().split()
mark_lst=[]
id_lst=[]
for i in range(red):
  mark_lst.append(int(arr2[i]))
  id_lst.append(int(arr1[i]))
for i in range(red):
  idx=i
  for j in range(i+1,red):
    if mark_lst[idx]<mark_lst[j]:
      idx=j
    if mark_lst[idx]==mark_lst[j]:
      if id_lst[idx]>id_lst[j]:
        idx=j
  mark_lst[i],mark_lst[idx] = mark_lst[idx], mark_lst[i]
  id_lst[i], id_lst[idx] = id_lst[idx], id_lst[i]

for i in range(red):
  output_file.write(f"ID: {id_lst[i]} Marks: {mark_lst[i]}\n")

input_file.close()
output_file.close()