# -*- coding: utf-8 -*-
"""CSE221 lab1 task 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XsgFObO0fRzPWX0-3DtdCpy72MwHPP38
"""

input_file=open("input4.txt","r")
num = int(input_file.readline())
trains = []
for i in range(num):
    words = input_file.readline().split(" ")
    train_name = words[0]
    destination = words[4]
    departure_time = words[6]
    trains.append([train_name, destination, departure_time])

n = len(trains)
for i in range(n-1):
    for j in range(n-i-1):
        if trains[j][0] > trains[j+1][0]:
            trains[j], trains[j+1] = trains[j+1], trains[j]
for i in range(n-1):
    for j in range(n-i-1):
        if trains[j][0] == trains[j+1][0] and trains[j][2] < trains[j+1][2]:
            trains[j], trains[j+1] = trains[j+1], trains[j]
input_file = open("input4.txt","r")
output_file = open("output4.txt","w")
for x in trains:
    output_file.write(f"{x[0]} will departure for {x[1]} at {x[2]}")
output_file.close()