# -*- coding: utf-8 -*-
"""CSE221 lab1 task 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XsgFObO0fRzPWX0-3DtdCpy72MwHPP38
"""

def bubbleSort(arr):
    checker=True
    for i in range(len(arr)-1):
        if checker==False:
            break
        checker=False
        for j in range(len(arr)-i-1):
            if arr[j]>arr[j+1]:
                arr[j],arr[j+1]=arr[j+1],arr[j]
                checker=True


input_file=open("input2.txt",'r')

red=input_file.readline()
arr1=input_file.readline().split()
arr=[]
for x in range(len(arr1)):
    arr.append(int(arr1[x]))
bubbleSort(arr)
output_file=open("output2.txt",'w')
for num in arr:
    output_file.write(str(num) +" ")
output_file.close()